iahm_page_home:
    path:     /
    defaults: { _controller: iahmPageBundle:Default:home }


iahm_page_mail_test:
    path:     /intercesseurs/merci
    defaults: { _controller: iahmPageBundle:Default:intercessorsThanks }

iahm_page_mail_test:
    path:     /thanks
    defaults: { _controller: iahmPageBundle:Default:thanks }

iahm_page_mail_test:
    path:     /mail_test
    defaults: { _controller: iahmPageBundle:Default:mailTest }

iahm_page_contact:
    path:     /contact
    defaults: { _controller: iahmPageBundle:Contact:contact }

iahm_page_custom:
    path:     /{name}
    defaults: { _controller: iahmPageBundle:Default:speaker }



