iahm_page_home_default:
    path:     /
    defaults: { _controller: iahmPageBundle:Default:home }

iahm_page:
    resource: "@iahmPageBundle/Resources/config/routing.yml"
    prefix:   /conference/

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
